version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: tasks_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasksdb       # 👈 aquí creará automáticamente la base
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2g

volumes:
  pg_data:
